theme: jekyll-theme-midnight
title: "Murlidhar Sharma's Portfolio"
description: "Data Analytics work examples"
align: center
classes: wide

name: Murlidhar Sharma
url: https://www.linkedin.com/in/murlis97/

google_analytics: UA-190985420-1
